- hosts: vault
  become_user: root
  become: true
  tasks:
    - name: install gnupg
      apt:
        name: gnupg
        update-cache: yes
        state: present
    - name: add Hashicorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: add Hashicorp repo
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    - name: install Vault
      apt:
        name: vault
        update-cache: yes
        state: present
    - name: create Vault data directory
      file:
        path: ./vault/data
        state: directory
        mode: u+rwx
# next, upload config https://learn.hashicorp.com/tutorials/vault/getting-started-deploy?in=vault/getting-started
# FULL TODO
# install Vault
# Use Vault to store secrets to use in Terraform
# Use Terraform to install k8s
# Use helm to install Rancher
# Use k8s to install AWX
