- hosts: vault
  become_user: root
  become: true

  tasks:
    - name: install squid-deb-proxy-client
      ansible.builtin.apt:
        name: squid-deb-proxy-client
        state: present
        update-cache: true
    - name: install gnupg
      ansible.builtin.apt:
        name: gnupg
        update-cache: true
        state: present
    - name: add Hashicorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: add Hashicorp repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    - name: install Vault, python3, and python3-pip
      ansible.builtin.apt:
        name: "{{ item }}"
        update-cache: true
        state: present
      loop:
        - vault
        - python3
        - python3-pip
    - name: install psutil
      ansible.builtin.pip:
        name: psutil
        state: present
    - name: update config to listen on machine's IP address
      ansible.builtin.replace:
        path: vault-config.hcl
        regexp: (127.0.0.1)
        replace: "{{ ansible_default_ipv4.address }}"
      become: false
      delegate_to: localhost
    - name: copy config
      ansible.builtin.copy:
        src: vault-config.hcl
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: u+rw
    - name: enable and start Vault service
      ansible.builtin.systemd:
        name: vault
        enabled: true
        state: started
    - name: check for Vault initialization file
      ansible.builtin.stat:
        path: vault_details.txt
      register: vault_details
    - name: initialize Vault
      ansible.builtin.command:
        cmd: vault operator init
      register: vault_output
      when: not vault_details.stat.exists
      environment:
        VAULT_ADDR: "http://{{ ansible_default_ipv4.address }}:8200"
    - name: echo vault output
      ansible.builtin.debug:
        msg: "{{ vault_output }}"
    - name: save Vault init output
      ansible.builtin.copy:
        dest: vault_details.txt
        content: "{{ vault_output.stdout  }}"
        owner: root
        mode: 0600
      when: not vault_details.stat.exists
    - name: get key details from init file
      ansible.builtin.command:
        cmd: cat vault_details.txt
      when: true
      register: init_details
    - name: get vault status
      ansible.builtin.command:
        cmd: vault status
      ignore_errors: true # always returns with non-zero
      environment:
        VAULT_ADDR: "http://{{ ansible_default_ipv4.address }}:8200"
      register: vault_status_text
      when: true
    - name: check if vault is sealed
      ansible.builtin.set_fact:
        vault_sealed: "{{ vault_status_text.stdout_lines[4]| regex_search('^Sealed.*(true|false)', '\\1') }}"
    - name: unseal Vault with Key 1
      ansible.builtin.command:
        cmd: "vault operator unseal {{ init_details.stdout_lines[0] | regex_replace('(?:Unseal Key [0-9]{1}:) (.*)', '\\1') }}"
      when: vault_sealed[0] == 'true'
      environment:
        VAULT_ADDR: "http://{{ ansible_default_ipv4.address }}:8200"
    - name: unseal Vault with Key 2
      ansible.builtin.command:
        cmd: "vault operator unseal {{ init_details.stdout_lines[1] | regex_replace('(?:Unseal Key [0-9]{1}:) (.*)', '\\1') }}"
      when: vault_sealed[0] == 'true'
      environment:
        VAULT_ADDR: "http://{{ ansible_default_ipv4.address }}:8200"
    - name: unseal Vault with Key 3
      ansible.builtin.command:
        cmd: "vault operator unseal {{ init_details.stdout_lines[2] | regex_replace('(?:Unseal Key [0-9]{1}:) (.*)', '\\1') }}"
      when: vault_sealed[0] == 'true'
      environment:
        VAULT_ADDR: "http://{{ ansible_default_ipv4.address }}:8200"
# FULL TODO
# ~~install Vault~~
# Use Vault to store secrets to use in Terraform
# Use Terraform to install k8s
# Use helm to install Rancher
# Use k8s to install AWX
