- hosts: apt-repo
  become_user: root
  become: true

  tasks:
    - name: install squid-deb-proxy
      ansible.builtin.apt:
        name: "{{ item }}"
        update-cache: true
        state: present
      loop:
        - squid-deb-proxy
    - name: remove squid service
      ansible.builtin.systemd:
        enabled: false
        state: stopped
        name: squid
        force: true
