- hosts: maas
  become_user: root
  become: true

  tasks:
    - name: install squid-deb-proxy-client
      apt:
        name: squid-deb-proxy-client
        state: present
        update-cache: yes
    - name: install gnupg
      apt:
        name: gnupg
        update-cache: yes
        state: present
    - name: add MAAS repo
      apt_repository:
        repo: ppa:maas/3.1
    - name: install maas
      apt:
        name: "{{ item }}"
        update-cache: yes
        state: present
      loop:
        - maas
