- hosts: maas
  become_user: root
  become: true

  tasks:
    - name: get MAAS username/password from Vault
      ansible.builtin.set_fact:
        maas: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/maas', auth_method='userpass', username=lookup('env', 'VAULT_USERNAME'), password=lookup('env', 'VAULT_PASSWORD'), url='http://vault:8200') }}"
      when: ansible_local.maas is undefined
    - name: install squid-deb-proxy-client
      ansible.builtin.apt:
        name: squid-deb-proxy-client
        state: present
        update-cache: true
    - name: install gnupg
      ansible.builtin.apt:
        name: "{{ item }}"
        update-cache: true
        state: present
      with_items:
        - gnupg
    - name: add MAAS repo
      ansible.builtin.apt_repository:
        repo: ppa:maas/3.1
    - name: install maas
      ansible.builtin.apt:
        name: "{{ item }}"
        update-cache: true
        state: present
      with_items:
        - maas
    - name: initialize MAAS
      ansible.builtin.command:
        cmd: "maas init --admin-username {{ maas.username }} --admin-email {{ maas.email }} --admin-password {{ maas.password }} --admin-ssh-import {{ maas.gh }} --rbac-url '' --candid-agent-file ''"
      when: ansible_local.maas is undefined
    - name: "add maas init fact to the system"
      ansible.builtin.copy:
        src: facts.d/maas.fact
        dest: /etc/ansible/facts.d/
        mode: 0600
      when: ansible_local.maas is undefined
